### ISSUE TITLE
E/ACameraMetadata: getConstEntry: cannot find metadata tag 65578

### ISSUE THREAD

**Issue by NolanOfficial** [google-ar/arcore-android-sdk#982]
### SPECIFIC ISSUE ENCOUNTERED
<img width="1676" alt="Screen Shot 2020-01-06 at 11 31 34 AM" src="https://user-images.githubusercontent.com/11055140/71832143-4d575800-3078-11ea-920d-f2f36d7f2eb6.png">

I've attached a Logcat preview above, but this bug seems to be pretty straightforward. The following error will get printed into the console recursively once a user has entered an AR Session: `E/ACameraMetadata: getConstEntry: cannot find metadata tag 65578`

I've also tested this on the Google's Example App and the same issue occurs. I've tested about 7 phones and each phone has had the same issue, with some constantly printing (Samsung Galaxies), and others printing the error every so often. 

### VERSIONS USED
- Android Studio: 3.5.2
- ARCore SDK for Android: 13.0, 14.0
- Device manufacturer, model, and O/S: Samsung Galaxy S10 OS 9
- ARCore: 
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 
Packages:
    versionName=1.14.191118106
Hidden system packages:
    versionName=0
samsung/beyond1qltesq/beyond1q:9/PPR1.180610.011/G973USQS1ASD9:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Open up android studio AR project
 2. Run the project on any device
 3. Start an AR Session
 4. Errors will start printing out inside of Logcat

### WORKAROUNDS (IF ANY)
None Found

**Comment by NolanOfficial** [comment]
The issue appears to stem from the following function call: 


![Screen Shot 2020-01-06 at 1 19 40 PM](https://user-images.githubusercontent.com/11055140/71923753-b82d8f80-315b-11ea-84cb-e95118820d3f.png)

I've tried to see if I can override some camera metadata properties but since they are immutable, I've had no luck.

**Comment by ajorias** [comment]
Same issue here, it's super annoying ESPECIALLY when debugging stuff.

**Comment by AntiGuide** [comment]
This happens for me too

VERSIONS USED

    Android Studio: 3.5.2
    Device manufacturer, model, and O/S: Samsung Galaxy S8 OS 9
    Output of adb shell getprop ro.build.fingerprint: samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXS6DSL2:user/release-keys
    versionName=1.14.191118106

**Comment by MichealReed** [comment]
Seeing this as well. The amount of log spam coming from ARCore probably isn't helping performance much.

**Comment by AntonioNoack** [comment]
Having this issue, too;
Android Studio 3.5.3, app based on HelloSceneView example.

**Comment by japser36** [comment]
Seems to be a duplicate of [#951](https://github.com/google-ar/sceneform-android-sdk/issues/951)

**Comment by fredsa** [comment]
This issue should be fixed in [Google Play Services for AR](https://play.google.com/store/apps/details?id=com.google.ar.core) 1.15.0 and later. As of today, the update is available to 100% of users on ARCore supported devices. For testing purposes, the APK is available for download and side loading from https://github.com/google-ar/arcore-android-sdk/releases

**Comment by ShantanuPhatke** [comment]
> This issue should be fixed in [Google Play Services for AR](https://play.google.com/store/apps/details?id=com.google.ar.core) 1.15.0 and later. As of today, the update is available to 100% of users on ARCore supported devices. For testing purposes, the APK is available for download and side loading from https://github.com/google-ar/arcore-android-sdk/releases

Despite of using the latest version I'm facing the same issue

**Comment by SarvagyaVaish** [comment]
Ditto. Still seeing the issue with
```    
    implementation 'com.google.ar:core:1.15.0'
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.15.0'
    implementation 'com.google.ar.sceneform:core:1.15.0'
```

**Comment by tellypresence** [comment]
Still seeing this with sceneForm `v1.16.0`, Android Studio 4.0 beta

**Comment by DipanshuHarbola** [comment]
Facing the same error - `E/ACameraMetadata: getConstEntry: cannot find metadata tag 65578`
Anyone have a solution or any workaround for this issue.

**Comment by nguyenbs** [comment]
This error still occurred in latest version v1.20.0
![image](https://user-images.githubusercontent.com/4568193/98455405-b6c95b00-21a2-11eb-9b73-149b6c102233.png)

**Comment by SunitRoy2703** [comment]
count 1 more

**Comment by johnjake** [comment]
the error was cause by missing <uses-feature android:name="android.hardware.camera.ar" android:required="true" /> in manifest

**Comment by ROBYER1** [comment]
Same issue here, Unity built app luckily it's just a test app but the log is spammed out!

**Comment by SunitRoy2703** [comment]
I resolved the problem currently, But didn't understood how it when,
what I did was just to rebuild the project

**Comment by MichealReed** [comment]
@fredsa can you reopen? Maybe this should spark a larger discussion about log overhaul. In release builds the output shouldn't even be piped to the console. Writing/keeping text is expensive.

**Comment by fredsa** [comment]
@MichealReed @ROBYER1 Please feel free to create a new issue with the specific log spam you're seeing in the latest SDK. Helpful to full log of an AR session, and report # of messages per second / per minute.

**Comment by ROBYER1** [comment]
> @MichealReed @ROBYER1 Please feel free to create a new issue with the specific log spam you're seeing in the latest SDK. Helpful to full log of an AR session, and report # of messages per second / per minute.

Put my issue in here, I was able to reproduce the error with any ARCore app, even the Google Measure app. The error for me is "Error ACameraMetadata getConstEntry: cannot find metadata tag 65576"

https://github.com/google-ar/arcore-android-sdk/issues/1166

**Comment by dkmoon** [comment]
Testing augmented face java. The same issue happening. ARCore 1.26.0.
